### ISSUE TITLE
Polish after deploy

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/user-extended-app#112]
- [x] On import -> file select -> show spinner at the very start.
- [x] On import start, /orgUnits load takes a lot, use filter by displayName:in, also for userRoles and userGroups.
- [x] Review translation key (missing: "override existing user") [@adrianq]
- [x] Trash icon disappears in some cases. [@adrianq]
- [x] Limit number of warnings in import table.
- [x] Cut imported rows to maxUsers and add warning.
- [x] Some users cannot be deleted (username_8) -> 500 -> APPARENTLY, DB PROBLEM, NOTHING TO DO.
- [x] Show also username in warning -> `Value not found: ${missingValue} [username=${username} csv-row=${rowIndex} column=${modelName}]`

https://docs.google.com/spreadsheets/d/1i4ZXX5SpAa1MTsplvdcOAnUlp_WiP2cZMPKWed3K8Cg/edit?ts=5bd2e56f#gid=0

**Comment by adrianq** [comment]
@tokland I have pushed the changes regarding the deployement context path. Can you please double check with your local changes if they are equivalent? These ones seem to work fine locally and in a remote server. I couldn't reproduce the delete icon issue but I found this minor issue https://github.com/EyeSeeTea/user-extended-app/issues/119. Updated as well the excel sheet with some comments. Merging this now...

**Comment by adrianq** [comment]
@tokland I have pushed the changes regarding the deployment context path. Can you please double check with your local changes if they are equivalent? These ones seem to work fine locally and in a remote server. I couldn't reproduce the delete icon issue but I found this minor issue https://github.com/EyeSeeTea/user-extended-app/issues/119. Updated as well the excel sheet with some comments. Merging this now...

**Comment by tokland** [comment]
Your code is spot on, pretty much the same I had. Tested, it works in dev and as app.

**Comment by adrianq** [comment]
Thanks @tokland !
