### ISSUE TITLE
[GEN] Implement disabled column on import/export

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/user-extended-app#139]
Related issues: https://github.com/EyeSeeTea/user-extended-app/pull/132

Client: WHO (General Maintenance)
Redmine: http://who-dev.essi.upc.edu:8083/issues/2700

**Comment by SferaDev** [comment]
WHO finds this would be useful and we will try to implement it soon.

**Comment by adrianq** [comment]
Moved to clickup
