### ISSUE TITLE
Update dependencies and simplify dev toolchain

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/user-extended-app#145]
## Current state

Trying to install the whole stack I found out that node-sass version was outdated and had an issue with newer dependencies and failed to compile during the gyp phase.

The host machine needs to include ruby and at least 4 gems (compass, susy, breakpoint and normalize-scss).

The application is stuck in using webpack v1 (current version is v4) and babel v6 (current version is v7).

Also we either need to force yarn resolutions for ```websockets``` packages to latest version (utf-8-validate and bufferutil) or we are stuck in older versions of node (v8 works fine but newer versions like v12 does not compile correctly the outdated versions we currently track of those packages).

## Proposal

With the next big feature version bump we should either migrate the codebase to CRA or the new DHIS app shell (depending on the status).

We should decouple the app from the direct dependency of d2-ui@27 and migrate to [EyeSeeTea/d2-ui-components](https://github.com/EyeSeeTea/d2-ui-components) (DataTable, ...). This will mean removing our fork and using npm packaging instead.

Compiled stylesheets such as scss should be simplified and we should not ask for the host computer to install compass, node should handle all the build tasks.

**Comment by adrianq** [comment]
Closing this for now. A major change would require a complete revamp of the architecture and dependencies
