### ISSUE TITLE
[GEN] Organisation unit encoding on import

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/user-extended-app#162]
Client: WHO (General Maintenance)
Redmine: http://who-dev.essi.upc.edu:8083/issues/2698

Import fails with encoded characters (specially on OUs), we should investigate the errors that fail and make more robust the equality comparison on import.

**Comment by SferaDev** [comment]
After several tests I have been unable to replicate the behavior (tested with "Cádiz", "Côte d'Ivoire" and "Kasaï").

Will ask for more details to Ina (who reported the issue) tomorrow.

![image](https://user-images.githubusercontent.com/2181866/67639992-3e755c00-f8f7-11e9-933b-3a82f067b37b.png)

**Comment by adrianq** [comment]
Moved to clickup
