### ISSUE TITLE
[GEN] Increase user import limit

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/user-extended-app#163]
Client: WHO (General Maintenance)
Redmine: http://who-dev.essi.upc.edu:8083/issues/2697

The number of users in import are limited by 200, we should investigate if there's a limitation in DHIS2 to enforce that. Also take in account React rendering time and resource management.

Possible solutions:

- Disable maxUsers and allow any kind of import
- Increase maxUsers to a real maximum within limitations of DHIS2
- Handle the import in batches if the limitation is really 200.

Right now, when importing the users (sometimes around 2.5k) we need to split them by groups of 200 and do manual imports of CSV files (12 times).

**Comment by adrianq** [comment]
Moved to clickup
