### ISSUE TITLE
Copy user configuration to other users

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/user-extended-app#172]
- [x] When clicking on "Copy User, show a modal dialog
- [x] Dialog should contain two toggles "user groups" and "user roles"
- [x] Implement logic to copy user groups
- [x] Add logic to copy user groups and/or user roles

-------------------------------
- [x] Add new contextual action "Copy in User"
- [x] Action should open a modal dialog
- [x] Show a multiple selector in the dialog with the available users in the DHIS2
- [x] On save, copy the user roles to the selected users. We should merge the user roles from the origin with the user roles of the destination users.

-------------------------------
For the future:

Tracking: http://who-dev.essi.upc.edu:8083/issues/3376

Allow to copy configuration from a user as a template to multiple existing users.

Use-case: Template user "WIDP Admin" applied to new members.
    - [ ] Allows to select: OU/CaptureOU
    - [ ] Replace/Merge options

**Comment by adrianq** [comment]
Pending tasks moved to clickup
