### ISSUE TITLE
Implement table layout settings

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-extended-app#71]
- [x] Add gear icon on right top corner in table
- [x] Implement Dialog. Available fields firstName, surname, username, email, lastUpdated, created, roles, groups, OUCapture, OUOutput, lastLogin. Changes are rendered on the fly. Use d2-ui GroupEditorWithSorting.
- [x] Implement Get/Post Calls to user data store

* On init, if no layout is found load current layout

Estimation: 15h

**Comment by tokland** [comment]
There is an option we didn't discuss for the fields dialog:  simply using a multiselector with ordering (https://github.com/dhis2/d2-ui/blob/v29.0.7/src/group-editor/GroupEditorWithOrdering.component.js), it's a typical UI for this kind of things.
