### ISSUE TITLE
Filters box

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-extended-app#73]
- [x] Redesign filter layout. By default only Search by name will show up. Rest of the filters will show up when clicking on filter button (https://material.io/tools/icons/?icon=filter_list&style=baseline). If any filter is active this icon will be highlighted. Clicking on the filter icon will toggle the filter box visibility. Suggested filter groups: OUCapture/OUOutput, Roles/Groups and Display my users
- [x] Add two new filters (OUCapture and OUOutput). We can reuse OU Tree component (See New Dataset in Maintenance App). We have to add a checkbox 'Include children OUs' (API field: includeChildren)

Estimation: 12h

**Comment by adrianq** [comment]
@adrianq to ask @ifoche if 'SELECT ALL' can do the trick instead of includeDescendant. See http://dev.eyeseetea.com:8080/dhis-web-maintenance/#/edit/dataSetSection/dataSet/add

**Comment by adrianq** [comment]
@tokland  I talked to Nacho.  Any option works for him but double checking the user api it looks like there is a parameter to include OU children. See https://docs.dhis2.org/master/en/developer/html/webapi_users.html and look for includeChildren. So maybe it is better to go for the checkbox as the performance is probably gonna be better. Let's talk tomorrow!

**Comment by tokland** [comment]
Regarding the limits on filters, reported as feature: https://jira.dhis2.org/browse/DHIS2-4646
