### ISSUE TITLE
Import feature

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/user-extended-app#74]
- [x] On click on import submenu open upload file explorer.
- [x] Available fields to be imported: firstName, surname, password, username, email, roles or userRoles, groups or userGroups, OUCapture or organisationUnits, OUOutput or dataViewOrganisationUnits and any other first level field (only basic fields (e.g.: string, number)). Password field is compulsory. 
- [x] Display table with users to be imported (reuse replicate table component). Horizontal and vertical scrolls. Table will highlight existing users. Existing users on top.
- [x] Add toggle component when existing users are found: 'Overwrite existing users'. If there are existing users and <overwrite existing users> is set to "false", import button should be disabled.
- [x] Implement import logic for csv. Overwrite always fields present in CSV
- [x] Errors and warning report. (e.g. non-existence organisationunits/roles, permissions, incorrect first level fields)

Estimation: 35h

**Comment by tokland** [comment]
- [ ] Existing users: chip N-E -> hover title "User already exists: ID". 
- [ ] Toggle: if disabled -> highlight row + chip N.e if enabled -> no highlight row but keep chip.
- [ ] Multiselect -> 1) if empty, empty string not [0], 2) Cursor mouse.

**Comment by adrianq** [comment]
Performance improvements:
- [ ] Check if components should be updated/refreshed (shouldcomponentupdate)
- [ ] Try  throttle approach to key events
