### ISSUE TITLE
Document latest features

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/user-extended-app#98]
https://docs.google.com/document/d/1XdU57_WvAEJv-grdnXkpqh1K9DY5QUYl-8Bl0vEuboM/edit

- [x] #73 Filters box
- [x] #71 Table layouts
- [x] #72 Export
- [x] #74 Import (https://docs.google.com/document/d/1kghfpv2G-OfMMUlo6kVl-cQ5jTTdAiMlhiXDVgz0atc/edit?usp=sharing)

**Comment by adrianq** [comment]
Reviewed official documentation. Updated: supported DHIS2 versions, remove action, a few screenshot, dev server, etc.

Import feature documentation will be reviewed for the next release

**Comment by ifoche** [comment]
Some comments after reviewing the documentation:
- I've added WHO description
- At least the following screenshots would need an update so they look like the app's now:

1) Page 9, under landing page title
2) Page 10, under layout settings
3) Page 11, under Export to CSV
4) Page 19, both screenshots

- In the summary of actions on page 22, there's no mention to Enable/Disable feature

**Comment by adrianq** [comment]
These are the release notes: https://github.com/EyeSeeTea/user-extended-app/releases/tag/v0.2.1
